env:
  node: true

extends:
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 9
  project: ./tsconfig.json
  sourceType: module

plugins:
  - '@typescript-eslint'
